# Install the pre-commit hooks below with
#   pre-commit install
# Update hook versions with
#   pre-commit autoupdate
# Run all hooks locally with
#   pre-commit run --all-files

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: end-of-file-fixer
    files: \.(py|pyi|rst|yml|yaml|toml)$
  - id: trailing-whitespace
  - id: debug-statements
    files: \.py$
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ["--maxkb=500"]
  - id: check-json
  - id: check-yaml
  - id: check-toml

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]

- repo: https://github.com/pycqa/flake8
  rev: '7.1.0'
  hooks:
  - id: flake8
